train_params:
  task_name: "finetunig"
  vqvae_autoencoder_ckpt_name: "vqvae_autoencoder_ckpt.pth"
  ldm_ckpt_name: "ddpm_ckpt_text_cond_clip.pth"
  num_samples: 1
  cf_guidance_scale: 5.0

autoencoder_params:
  z_channels: 4
  codebook_size : 8192
  down_channels : [64, 128, 256, 256]
  mid_channels : [256, 256]
  down_sample : [True, True, True]
  attn_down : [False, False, False]
  norm_channels: 32
  num_heads: 4
  num_down_layers : 2
  num_mid_layers : 2
  num_up_layers : 2

ldm_params:
  down_channels: [ 256, 384, 512, 768 ]
  mid_channels: [ 768, 512 ]
  down_sample: [ True, True, True ]
  attn_down : [True, True, True]
  time_emb_dim: 512
  norm_channels: 32
  num_heads: 16
  conv_out_channels : 128
  num_down_layers : 2
  num_mid_layers : 2
  num_up_layers : 2

  condition_config:
    condition_types: ["text"]
    text_condition_config:
      text_embed_model: clip
      placeholder_token: me
      embedding_path: embeddings/me.pt
      image_path: data/myfaceimages/my_face0.jpg



dataset_params:
  caption_file: "data/myfaceimages/captions.txt"
  im_path : data/myfaceimages/
  im_size: 256
  im_channels: 3

diffusion_params:
  beta_start: 0.0001
  beta_end: 0.02
  num_timesteps: 1000


